vagrant_hostname: cucas8vmcd.test
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the drupal-vm folder.
  - local_path: ./sites/zlatan
    destination: /var/www/zlatan
    type: nfs
    create: false
  - local_path: ./sites/rojo
    destination: /var/www/rojo
    type: nfs
    create: false
drupal_install_site: false
drupal_build_composer_project: false
drupal_build_composer: false
drupal_composer_path: false
drupal_composer_install_dir: "/var/www/zlatan"
drupal_composer_dependencies: []
drupal_core_path: "{{ drupal_composer_install_dir }}/docroot"
# Settings for installing a Drupal site if 'drupal_install_site:' is 'true'.
#drupal_major_version: 8
#drupal_domain: "{{ vagrant_hostname }}"
#drupal_site_name: "Drupal"
#drupal_install_profile: standard
#drupal_enable_modules: []
#drupal_account_name: admin
#drupal_account_pass: admin
# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, set this value to an empty set, e.g. `[]`.
installed_extras:
  - adminer
  # - blackfire
  - drupalconsole
  - drush
  # - elasticsearch
  # - java
  - mailhog
  # - memcached
  # - newrelic
  # - nodejs
  - pimpmylog
  # - redis
  # - ruby
  # - selenium
  # - solr
  # - tideways
  # - upload-progress
  - varnish
  # - xdebug
  # - xhprof # use `tideways` if you're installing PHP 7+
firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "81"
  - "443"
  - "3306"
  - "4444"
  - "8025"
  - "8080"
  - "8443"
  - "8983"
  - "9200"
# Apache VirtualHosts. Add one for each site you are running inside the VM. For
# multisite deployments, you can point multiple servernames at one documentroot.
# View the geerlingguy.apache Ansible Role README for more options.
apache_vhosts:
  - servername: "{{ vagrant_hostname }}"
    serveralias: "www.{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "adminer.{{ vagrant_hostname }}"
    documentroot: "{{ adminer_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "xhprof.{{ vagrant_hostname }}"
    documentroot: "{{ php_xhprof_html_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "pimpmylog.{{ vagrant_hostname }}"
    documentroot: "{{ pimpmylog_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "{{ vagrant_ip }}"
    serveralias: "dashboard.{{ vagrant_hostname }}"
    documentroot: "{{ dashboard_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
# multisite settings
  - servername: "local.drupal_two.{{ vagrant_hostname }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.drupal_three.{{ vagrant_hostname }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.8a.{{ vagrant_hostname }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.8b.{{ vagrant_hostname }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.8c.{{ vagrant_hostname }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "local.8d.{{ vagrant_hostname }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "rojo.{{ vagrant_hostname }}"
    documentroot: "/var/www/rojo/web"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

# MySQL databases
mysql_databases:
  - name: "{{ drupal_db_name }}"
    encoding: utf8mb4
    collation: utf8mb4_general_ci
  - name: drupal_two
    encoding: utf8
    collation: utf8_general_ci
  - name: drupal_three
    encoding: utf8
    collation: utf8_general_ci
  - name: drupal_a
    encoding: utf8
    collation: utf8_general_ci
  - name: drupal_b
    encoding: utf8
    collation: utf8_general_ci
  - name: drupal_c
    encoding: utf8
    collation: utf8_general_ci
  - name: drupal_d
    encoding: utf8
    collation: utf8_general_ci
  - name: rojo
    encoding: utf8
    collation: utf8_general_ci
mysql_users:
  - name: drupal
    host: "%"
    password: drupal
    priv: "drupal*:ALL"
  - name: drupal-two
    host: "%"
    password: drupal-two
    priv: "drupal_two.*:ALL"
  - name: drupal-three
    host: "%"
    password: drupal-three
    priv: "drupal_three.*:ALL"
  - name: rojo
    host: "%"
    password: rojo
    priv: "rojo.*:ALL"
