vagrant_hostname: fellaini.local
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the drupal-vm folder.
  - local_path: ./sites/rojo
    destination: /var/www/rojo
    type: nfs
    create: false
  - local_path: ./sites/fellaini
    destination: /var/www/fellaini
    type: nfs
    create: false
  - local_path: ./sites/philjones
    destination: /var/www/philjones
    type: nfs
    create: false
vagrant_memory: 4096
drupal_install_site: false
drupal_build_composer_project: false
drupal_build_composer: false
drupal_composer_path: false
drupal_composer_install_dir: "/var/www/fellaini/"
drupal_composer_dependencies: []
drupal_core_path: "{{ drupal_composer_install_dir }}/web"
configure_drush_aliases: true
# Settings for installing a Drupal site if 'drupal_install_site:' is 'true'.
#drupal_major_version: 8
#drupal_domain: "{{ vagrant_hostname }}"
#drupal_site_name: "Drupal"
#drupal_install_profile: standard
#drupal_enable_modules: []
#drupal_account_name: admin
#drupal_account_pass: admin
# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, set this value to an empty set, e.g. `[]`.
installed_extras:
  - adminer
  # - blackfire
  - drupalconsole
  - drush
  # - elasticsearch
  # - java
  # - mailhog
  # - memcached
  # - newrelic
  # - nodejs
  - pimpmylog
  # - redis
  # - ruby
  # - selenium
  # - solr
  # - tideways
  # - upload-progress
  - varnish
  #- xdebug
  # - xhprof # use `tideways` if you're installing PHP 7+
firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "81"
  - "443"
  - "3306"
  - "4444"
  - "8025"
  - "8080"
  - "8443"
  - "8983"
  - "9200"


# PHP Configuration. Currently-supported versions: 5.6, 7.0, 7.1, 7.2.
# See version-specific notes: http://docs.drupalvm.com/en/latest/configurations/php/
php_version: "7.2"
php_install_recommends: no
php_memory_limit: "512M"
php_display_errors: "On"
php_display_startup_errors: "On"
php_realpath_cache_size: "1024K"
php_sendmail_path: "/opt/mailhog/mhsendmail"
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "192"
php_opcache_max_accelerated_files: 4096
php_max_input_vars: "4000"
# Apache VirtualHosts. Add one for each site you are running inside the VM. For
# multisite deployments, you can point multiple servernames at one documentroot.
# View the geerlingguy.apache Ansible Role README for more options.
apache_vhosts:
  - servername: "{{ vagrant_hostname }}"
    documentroot: "/var/www/fellaini/web"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "adminer.{{ vagrant_hostname }}"
    documentroot: "{{ adminer_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "xhprof.{{ vagrant_hostname }}"
    documentroot: "{{ php_xhprof_html_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "pimpmylog.{{ vagrant_hostname }}"
    documentroot: "{{ pimpmylog_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "{{ vagrant_ip }}"
    serveralias: "dashboard.{{ vagrant_hostname }}"
    documentroot: "{{ dashboard_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
# multisite settings

  - servername: "second.{{ vagrant_hostname }}"
    documentroot: "/var/www/fellaini/web"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "people.{{ vagrant_hostname }}"
    documentroot: "/var/www/fellaini/web"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

# enable below for additional hostnames mapped to sites folders
#  - servername: "8c.{{ vagrant_hostname }}"
#    documentroot: "/var/www/fellaini/web"
#    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

#  - servername: "8d.{{ vagrant_hostname }}"
#    documentroot: "/var/www/fellaini/web"
#    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "rojo.{{ vagrant_hostname }}"
    documentroot: "/var/www/rojo/web"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "philjones.{{ vagrant_hostname }}"
    documentroot: "/var/www/philjones/web"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

# MySQL databases
mysql_databases:
  - name: second
    encoding: utf8
    collation: utf8_general_ci
  - name: people
    encoding: utf8
    collation: utf8_general_ci
# enable below to provision additional databases
#  - name: drupal_c
#    encoding: utf8
#    collation: utf8_general_ci
#  - name: drupal_d
#    encoding: utf8
#    collation: utf8_general_ci
  - name: rojo
    encoding: utf8
    collation: utf8_general_ci
  - name: fellaini
    encoding: utf8
    collation: utf8_general_ci
  - name: philjones
    encoding: utf8
    collation: utf8_general_ci
mysql_users:
  - name: drupal
    host: "%"
    password: drupal
    priv: "*.*:ALL"

# XDebug configuration. XDebug is disabled by default for better performance.
#php_xdebug_default_enable: 1
#php_xdebug_coverage_enable: 0
#php_xdebug_cli_disable: yes
#php_xdebug_remote_enable: 1
#php_xdebug_remote_connect_back: 1
#php_xdebug_idekey: sublime.xdebug
#php_xdebug_max_nesting_level: 256
#php_xdebug_remote_host: "{{ ansible_default_ipv4.gateway }}"
